name: FakePluginList
version: ${project.version}
main: tr.donsuzturk.fakepluginlist.Main
api-version: 1.17
authors: [ DonsuzTurk ]
description: Eklenti listenizi farklı şekilde görüntülemenizi sağlar.
